### ISSUE TITLE
update user creation implementation to handle invites

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#164]
## Task Description
Based on our new flow of sending invites to users for them to sign up. We will need to update our current implementation to handle certain checks and insert only required fields.

## Technical Considerations
1. We have a middleware on the `auth/create-user` route to ensure only admins can create users. This will no longer be the case so has to be removed
2. We only want to take in these four fields from the body: ` firstName`, `lastName`, `password` and `email`
3. Before creating the user, we need to verify the token that comes in and confirm if the `email` in the request body is present in the `user_invites` database and if it is the same as the one in the token.
4. If it checks out, the user is successfully created. If not, an appropriate error response is returned

**Comment by itzgeebee** [comment]
@jocrah Just want to clarify something, is the token going to be sent from the client as part of the request body or a parameter?

**Comment by jocrah** [comment]
@itzgeebee it can be  part of the request header, using the same `Bearer {token}` format and we can have a middleware to check that

Kindly let me know if it makes sense

**Comment by itzgeebee** [comment]
@jocrah It makes sense.
