### ISSUE TITLE
test create user endpoint

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#198]
## Task Description
Add test for the `auth/create-user` endpoint

## Technical Considerations
For this, we would like to have each route with its tests
1. Create a folder called `/users` in the `src/routes` folder and move the `users.js` into the  new `users` folder  
2. Rename the users.js into `index.js`
3. Create a `create-new-user.e2e.test.js` 
4. Use the`api` function in the util which uses the existing `supertest` package to use for our routes
5. The test cases should involve testing error scenarios based on the validation errors and status codes thrown in the logic and success scenarios

**Comment by itzgeebee** [comment]
@jocrah This is part of the auth.js file, should I still put it under users or should I create an auth file?

**Comment by jocrah** [comment]
> @jocrah This is part of the auth.js file, should I still put it under users or should I create an auth folder?

@itzgeebee  o okay, that skipped me, auth folder then
