### ISSUE TITLE
add table to record likes on posts

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#207]
## Task Description
In order to build a functionality to record likes on a post, we will need a table which will record information about the `like` on the post

## Technical Considerations
As we do for new changes to the database schema, we'll be using migrations. [Reference here](https://github.com/tbf-challenge/teamwork-be#how-do-i-add-a-new-migration).
1. Create a table called `post_likes` which will have the following fields:
  -  `postId`  - id of post being liked as a foreign key
  -  `userId`  - id of user liking the post as a foreign key
  - `createdAt` - date the post was liked

2. We will using the `postId` and `userId` as a composite primary key for the table

**Comment by jocrah** [comment]
@beblicarl, let's kindly tackle what is left of the 5th milestone, before taking this up. 

Kindly let me know if anything. Thanks

**Comment by beblicarl** [comment]
> @beblicarl, let's kindly tackle what is left of the 5th milestone, before taking this up.
> 
> Kindly let me know if anything. Thanks

yes please, i have unassigned myself
