### ISSUE TITLE
add table to record flagged posts

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#208]
## Task Description
In order to build a functionality to record posts that have been flagged for being inappropriate, we will need a table which will record information about the `flag` on the post

## Technical Considerations
As we do for new changes to the database schema, we'll be using migrations. [Reference here](https://github.com/tbf-challenge/teamwork-be#how-do-i-add-a-new-migration).
1. Create a table called `post_flags` which will have the following fields:
  -  `postId`  - id of post being flagged as a foreign key
  -  `userId`  - id of user flagging the post as a foreign key
  - `reason` - an optional field to record the reason the post is being flagged as inappropriate
  - `createdAt` - date the post was flagged

2. We will using the `postId` and `userId` as a composite primary key for the table

**Comment by jocrah** [comment]
haha any reason why you're assigned on multiple issues @beblicarl?

**Comment by beblicarl** [comment]
> haha any reason why you're assigned on multiple issues @beblicarl?

I was thinkng i will be able to work on those two within a short time frame
