### ISSUE TITLE
endpoint to unflag an article

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#225]
## Task Description
We need an endpoint to unflag an article

## Technical Considerations
1. We can have a `DELETE /articles/:id/flags/:userId` endpoint. Where `id` is the id of the article and  `userId`
2. This will delete the flag in the database

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by jocrah** [comment]
> Hi, I would like to work on this.

okay, assigning you
