### ISSUE TITLE
endpoint to flag an article as inappropriate

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#226]
## Task Description
We need an endpoint to flag an article

## Technical Considerations
1. We can have a `POST /articles/:id/flags` endpoint. Where `id` is the id of the article will take the `userId` and an optional `reason` in the body
2. This will be a new entry in the database if it does not exist already. the table in use will be the `post_flags` table
3. If it has already been flagged, throw an appropriate error

**Comment by then00bprogrammer** [comment]
hey @jocrah , i'd like to work on this, assign me.

**Comment by jocrah** [comment]
> hey @jocrah , I'd like to work on this, assign me.

done @then00bprogrammer
