### ISSUE TITLE
create user endpoint results in unexpected error about email

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#228]
## Describe the problem

Currently, when creating a new user with the valid details using the `/auth/create-user` endpoint, it results in an error that `email not found invites list` even though email actually has an invite

## Actual behavior
User creation should work

## Expected behavior
It ends in an error 

## Steps to reproduce
1. Use an admin user to send an invite to a user
2. Use the `token` to make a request to the `/auth/invite/token`
3. using the `accessToken` gotten from the preceding endpoint, call the `auth/create-user` to create a user with sample details and the right email 
4. It should result in an error about email not being in invites list

**Comment by itzgeebee** [comment]
> 2\. /auth/invite/token

@jocrah is there any endpoint like this though?

**Comment by jocrah** [comment]
> @jocrah is there any endpoint like this though?

@itzgeebee  typo sorry, its `/auth/invites/:token`
