### ISSUE TITLE
use right authentication specification in API docs

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#241]
## Task Description
Currently, we have documentation to outline what most of our routes need for requests. However,  for the endpoints which need some form of authentication, we use the wrong definition in our [docs specification](https://github.com/tbf-challenge/teamwork-be/blob/main/docs/swagger.yaml).

This is represented by a `security` parameter we're currently defining for such endpoints which does not work well because it is not well defined according to swagger specifications.

https://github.com/tbf-challenge/teamwork-be/blob/8f375dd44d7eb6bf78fc660140c0acae6580a747/docs/swagger.yaml#L80-L81

### Technical Reference
Here is some information to give an idea of the right way to go about this: https://swagger.io/docs/specification/authentication/bearer-authentication/

### Additional Consideration
As part of this task, any route which needs an authentication header to work but has no such specification in. the current docs should also be updated.

**Comment by jakazzy** [comment]
sure picked this up

**Comment by jakazzy** [comment]
On this now
