### ISSUE TITLE
allow profile picture field when creating a user

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#245]
## Task Description
In addition to the current fields we have in our endpoint for creating a user, we would like to allow an optional field for recording the profile picture of the user.

## Technical Considerations
1. Create a migration to add a new column. Since we already have a convention of using camel casing for our column names we can work with `profilePictureUrl` / `profileImageUrl` or simply `picture`.
2. Update the `/auth/create-user` endpoint to allow for the new field

**Comment by beblicarl** [comment]
good morning @jocrah , should the profile picture field be a required field?

**Comment by jocrah** [comment]
> good morning @jocrah , should the profile picture field be a required field?

greetings Carl, no please, should be optional

**Comment by jocrah** [comment]
I see you're assigned on two issues at the moment though, any reason?

**Comment by beblicarl** [comment]
> I see you're assigned on two issues at the moment though, any reason?

the very first issue i have left a message in the frontend channel to get all member inputs, while waiting i thought i could pick another issue and work on it

**Comment by jocrah** [comment]
> the very first issue i have left a message in the frontend channel to get all member inputs, while waiting i thought i could pick another issue and work on it

okay, inputs concerning?

**Comment by jocrah** [comment]
its not really dependent on the frontend

**Comment by jocrah** [comment]
we're documenting the endpoints that have no documentation

**Comment by beblicarl** [comment]
> > the very first issue i have left a message in the frontend channel to get all member inputs, while waiting i thought i could pick another issue and work on it
> 
> okay, inputs concerning?

it is an investigative issue like you said, i asked them to list all documentations they wanted me to improve and what improvement they wanted. They were the ones who complained about it in the first place

**Comment by jocrah** [comment]
Okay. I meant investigative as in looking through the code and documenting. we are the ones with the code, its just about us documenting it the way the code works

**Comment by beblicarl** [comment]
> Okay. I meant investigative as in looking through the code and documenting. we are the ones with the code, its just about us documenting the way the code works

oh okay, then i will unassign myself from this issue and focus on that one
