### ISSUE TITLE
Fix flaky test in code

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#287]
## Describe the problem
View the CI Build here:
https://github.com/tbf-challenge/teamwork-be/actions/runs/3372233769/jobs/5595420591

and fix the flaky test.
Also possible to trigger the build a few times to view flaky tests and fix them

### Identified So Far
- [ ] - Tags-related tests where we get a `title_unique` error when multiple tags are inserted. That is because the `title` column of the `tags` table is supposed to be unique. The proposed fix is to use a faker generator function which gives us less likelihood of clashes.

- [ ] - create-new-user service test which sometimes has an accessToken mismatch.

**Comment by jakazzy** [comment]
Looked into this for while. Cant seem to figure out the cause of the flaky test since it is not easily reproducible locally.
Therefore, as part of resolving the flaky test, the next steps being done in the PR is to add logs to the test and then monitor.
so that if it does occur again, it will be possible to appreciate the cause.

**Comment by jocrah** [comment]
We've worked on a few parts of this which have reduced flakiness. One more realised when pr was just merged came from this file. See the failed build [here](https://github.com/tbf-challenge/teamwork-be/actions/runs/3476989623/jobs/5812713401).

File being referenced: 
https://github.com/tbf-challenge/teamwork-be/blob/cea8b8a369ef1d3ef9dfba98e7c875b799d56d60/src/services/tags/update-tag.test.js


Fix is to set the title with a faker generator function which reduces the likelihood of clashes like we have done in other places
