### ISSUE TITLE
add test to create tag endpoint

### ISSUE THREAD

**Issue by beblicarl** [tbf-challenge/teamwork-be#298]
## Task Description

1. Add tests to the create tag endpoint & services
2. This is a subtask linked to https://github.com/tbf-challenge/teamwork-be/issues/243

## Technical Considerations

1. Basically, we are testing the create tag endpoint & services

**Comment by jocrah** [comment]
@beblicarl, so let's always add new issues created to current/new milestones (I just created another one) instead of outdated ones (e.g 8th milestone)

**Comment by beblicarl** [comment]
> @beblicarl, so let's always add new issues created to current/new milestones (I just created another one) instead of outdated ones (e.g 8th milestone)

alright, I will take note of that
