### ISSUE TITLE
Fix flaky test for get Tags

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#301]
## Describe the problem
View the build here: https://github.com/tbf-challenge/teamwork-be/actions/runs/3404965857/jobs/5662583791
The build fails. Let's fix the flaky  test

and here too
https://github.com/tbf-challenge/teamwork-be/actions/runs/3404958836/jobs/5662571929

**Comment by jocrah** [comment]
we'll keep track of this https://github.com/tbf-challenge/teamwork-be/issues/287, and create incremental prs as and when we find a flaky test

when we get to know the reason for the flaky test by probably a failing build or a local test failure, we'll state the reason in that issue and suggest a fix
