### ISSUE TITLE
compute and record number of flags every time a post is flagged/unflagged

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#308]
## Task Description
Currently, we have the functionality to record the number of times a post has been flagged as inappropriate. This is recorded in the `post_flags` table. 

With this in mind, whenever a post is being fetched, we would need to make a computational query on the `post_flags` table to get the count of the flags.

However, that could be expensive hence we want to approach this in a way that the number of likes for a post is already pre-computed and stored on the `posts` table itself.

Hence, this task is for us to a pre-computation of the number of likes and store it on the `posts` table

## Technical Considerations
1. Per our working theory as of now, we will be using the concept of database triggers. (This will mostly require a new migration as well. [Reference here on adding a new migration](https://github.com/tbf-challenge/teamwork-be#how-do-i-add-a-new-migration)).
2. With that, we want to make sure any addition/deletion which happens on the `post_flags` table, triggers a database function which will compute the number of times a specific post has been flagged and then store it in the `flags_count` field of that post

## References 
**Database Triggers Concept**
1. https://hevodata.com/learn/postgresql-triggers/
2. https://www.tutorialspoint.com/postgresql/postgresql_triggers.htm
3. https://www.postgresql.org/docs/current/sql-createtrigger.html

**Comment by jocrah** [comment]
i can confidently say this has not been tested in production

**Comment by jocrah** [comment]
> i can confidently say this has not been tested in production

@beblicarl

**Comment by beblicarl** [comment]
> i can confidently say this has not been tested in production

to be honest, I have been writing tests for endpoints for so long that I forgot we had to test others in production like we used to. Lmao

**Comment by jocrah** [comment]
> to be honest, I have been writing tests for endpoints for so long that I forgot we had to test others in production like we used to. Lmao

'for so long', wow :laughing:

**Comment by jocrah** [comment]
closing it though, to some extent you will not be able to test because we're not returning the `likesCount` as part of the api response
