### ISSUE TITLE
add test to assign tag to article endpoint

### ISSUE THREAD

**Issue by beblicarl** [tbf-challenge/teamwork-be#331]
## Task Description

1. Add tests to assign tag to article endpoint and assign tag to post service.
2. Create a separate file for the assignTagToPost function
3. This is a subtask linked to https://github.com/tbf-challenge/teamwork-be/issues/243

## Technical Considerations

Basically, we are testing the assign tag to article endpoint and assign tag to post service

**Comment by jakazzy** [comment]
cool @beblicarl
