### ISSUE TITLE
Add user login endpoint

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#40]
## Task Description

Describe the task to be completed.

Prior to creating the user login, create a super admin. The super admin(super admin should be seeded into the database)

Add user login endpoint. The user should be able to log in with an organizational email and password. 
## Technical Considerations
Email should be valid
password  validation rules
- Password should contain uppercase and lowercase letters.
- Password should contain letters and numbers.
- Password should contain special characters.
- Minimum length of the password (the default value is 8).
Include any technical considerations including architecture (e.g. API), required libraries, etc.

## Additional ConsiderationsS

Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by KemiDoyin** [comment]
@KemiDoyin

**Comment by Saviour-Dagadu** [comment]
Please can I join you guys on this issue? Please where have you gotten to on this?
