### ISSUE TITLE
Add user login template

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#41]
## Task Description

Describe the task to be completed.

Prior to creating the user login, create a super admin. The super admin(super admin should be seeded into the database)

Add user login template. The user should be able to log in with an organizational email and password. 
## Technical Considerations
Email should be valid
password  validation rules
- Password should contain uppercase and lowercase letters.
- Password should contain letters and numbers.
- Password should contain special characters.
- Minimum length of the password (the default value is 8).
Include any technical considerations including architecture (e.g. API), required libraries, etc.

## Additional Considerations
Ensure the login template is responsive and follows the design on figma -  https://www.figma.com/file/gU3GHIN3tuqKqPFfGvVaez/GITHUB
Validate the login details using either Yup https://www.npmjs.com/package/yup or Joi - https://www.npmjs.com/package/joi

**Comment by Saviour-Dagadu** [comment]
Please assign this to me I will start working on this right away.

**Comment by Saviour-Dagadu** [comment]
This is how I would be working on this

1. Display the login form with username, password, and submit button on the screen.
2. Users can input the values on the form.
3. Validate the username and password entered by the user.
4. Display an error message when the login fails.
5. Show success message when login is successful.
