### ISSUE TITLE
Add user creation endpoint

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#44]
## Task Description
Admin should be able to create a new user

An employee account should be created - POST /auth/create-user
The endpoint should accept the payload
I. first Name
ii. last Name
iii. Email
Iv. password
v. gender
vi. jobrole
vii. department
viii. Address
The password should be autogenerated
Describe the task to be completed.

## Technical Considerations

Include any technical considerations including architecture (e.g. API), required libraries, etc.

## Additional ConsiderationsS

Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by beblicarl** [comment]
1. I will get {first Name, last Name, Email, password, gender, jobrole , department, Address} from the request body
2. I will use pool.query and insert these variables into the db
3. I will throw an error if there is one or a 201 status response if successful
