### ISSUE TITLE
add endpoint for user should be able to create new article

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#45]
## Task Description

Describe the task to be completed.
Employees should be able to create articles
Articles created on platform should not exceed character limit of 63,206(or less)

**Comment by beblicarl** [comment]
How i will do this  @jakazzy 
1. npm install express pg  - I will install express and the pg library to interact with postgres db
2. Create an SQL file and build our db commands that we would be running on postgres
3.I will create an article db and create a table called articles as well as the schema
4. In our db.js file we attempt to connect to the database by creating a new instance of Pool and specify the (user, password, database, host and port)
5. Create routes with database queries (POST/articles)

**Comment by beblicarl** [comment]
1. For the config object am i supposed to create my own user and password?

**Comment by beblicarl** [comment]
1. The article should not exceed 63,206, how about the title of each article?
