### ISSUE TITLE
Technical Debt

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#84]
## These are technical debts to be handled. we'll clear these tasks for the week and move on to the next set of features.
Each of the listed items in the technical debt will be converted to a task for this week's milestone

- [x] Verify user if user isAuthenticated(for post and  tag creation etc)
- [x] refactor the passport.authenticate(jwt) middleware into a function with name isAuthenticated to be added as a middleware to the routes
- [x] Validation of data for the existing routes using joi
- [x] creating compound index for the posts and tag tables
- [x] refactor post creation so it follows the requirement specification in terms of the data the frontend expects
- [x] refactor the code to use services
- [x] error handling for tags 
- [x] Error handling for  creation of posts

**Comment by beblicarl** [comment]
1, Can you please explain what you mean by error handling for tags and creation of posts? @jakazzy 
2. Can you seperate the error handling for tags and the creation of posts?

**Comment by jakazzy** [comment]
@beblicarl  sure,
1.  do check this article out on error handling https://reflectoring.io/express-error-handling
2. Yes error handling for tags and post creation will be separated when the individual tasks are created
3. You can look at the example in the code here: https://github.com/tbf-challenge/teamwork-be/blob/main/src/services/users.js
You can begin from this [file](https://github.com/tbf-challenge/teamwork-be/blob/main/src/routes/index.js#L10) to appreciate the architecture

**Comment by beblicarl** [comment]
> @beblicarl sure,
> 
> 1. do check this article out on error handling https://reflectoring.io/express-error-handling
> 2. Yes error handling for tags and post creation will be separated when the individual tasks are created
> 3. You can look at the example in the code here: https://github.com/tbf-challenge/teamwork-be/blob/main/src/services/users.js
>    You can begin from this [file](https://github.com/tbf-challenge/teamwork-be/blob/main/src/routes/index.js#L10) to appreciate the architecture

Thank you

**Comment by jakazzy** [comment]
completed
