### ISSUE TITLE
Make post and tag unique

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#87]
## Task Description
Currently, we have a situation where while inserting we do an `INNER SELECT` to check if the tag has already been assigned to a post to prevent us from having multiple entries of the same post and tag.

https://github.com/tbf-challenge/teamwork-be/blob/50aa75e2e5e156ac37acfb0127c70ffb13de9251/src/routes/posts.js#L46

We want this to be handled at the database level instead so that even a manual insert into the database will also fail. 

Current working implementation is to add a unique constraint to the table for the `postId` and `tagId`.

**Comment by jocrah** [comment]
@itzgeebee just updated the issue description like i said

**Comment by itzgeebee** [comment]
> @itzgeebee just updated the issue description like i said

@jocrah Like a compound/composite primary key right?

**Comment by jocrah** [comment]
> @jocrah Like a compound/composite primary key right?

@itzgeebee  correct, its actually between the composite primary key and  then adding a unique constraint for the fields. 

either of them works for our purposes.

my curiosity led me to see some differences here: https://stackoverflow.com/a/14221810
