### ISSUE TITLE
Integrate TravisCI for Continuous Integration

### ISSUE THREAD

**Issue by Aajibolah** [tbf-challenge/teamwork-be#9]
## Task Description
Since we've started introducing testing, it would be great to have it run when we push commits to Github to ensure everything runs as expected

This will save time for the PR reviewers and prevent them from having to run the tests locally to ensure they pass

## Technical Considerations
1. Basic consideration is that we will need the same resources we need when running tests locally: `node`, a Postgres database and any more not mentioned.
2. We will need environmental variables for the tests to use in running

[This can be a good starting point on TravisCI](https://docs.travis-ci.com/user/for-beginners)

## Additional Considerations
1. We would likely need a teamwork account on TravisCI if not already created. Kindly contact Jida Asare so that can be arranged.
2. Same applies to any integration that needs to be done between the repo and TravisCI.
3. Add badge in README to give a status of the build

**Comment by beblicarl** [comment]
### This is how i am going to solve the problem
1. Create a travis ci account and connect it to this repository
2. Add a .travis.yml file to the root directory of the repository, specify the programming language used, the building and testing environment
3. Set up test script in my package.json and specify for travis ci to run ESlint using Airbnb style guide while skipping node_modules folder
4. Push to github
5.Go to Travis CI and select the repository you are interested in and click the badge icon next to the title
6.Select Markdown, copy the text below and copy paste it in the README.md file
7. Push to the repository and make a pull request

@jakazzy

**Comment by jakazzy** [comment]
@beblicarl great!

**Comment by jakazzy** [comment]
For this though we planned on going with travis ci. Currently we have changed to use github actions.

**Comment by jakazzy** [comment]
We integrated Github actions instead
