### ISSUE TITLE
Refactor post functionality to use services

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#92]
## Task Description

Describe the task to be completed.

Let's refactor post functionality so it uses services. 
we can follow the pattern/architecture for user creation right from the routes to how the response is sent. 
we want to separate the code from the express.js router
and also not pass the req or res object to the service layer.

**Comment by itzgeebee** [comment]
@jakazzy Please I need a bit more clarity on this task.

**Comment by jakazzy** [comment]
sure @itzgeebee It seems @beblicarl  may have began this I presume
@beblicarl can you kindly confirm if you are working on this?

**Comment by beblicarl** [comment]
> sure @itzgeebee It seems @beblicarl may have began this I presume @beblicarl can you kindly confirm if you are working on this?

I can confirm that i am working on this

**Comment by jakazzy** [comment]
yet to get a response but i see  @beblicarl has assigned himself.

**Comment by jakazzy** [comment]
> > sure @itzgeebee It seems @beblicarl may have began this I presume @beblicarl can you kindly confirm if you are working on this?
> 
> I can confirm that i am working on this

sure noted. 
@itzgeebee do let me know if you find any of interest https://github.com/tbf-challenge/teamwork-be/milestone/3

**Comment by itzgeebee** [comment]
@jakazzy I was already working on it before I got a message from @beblicarl  So I intend to finish it even if it won't be merged and I'll pick another task
