### ISSUE TITLE
Refactor tagging functionality to use services

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#94]
## Task Description

Describe the task to be completed.

Let's refactor tagging functionality so it uses services. 
we can follow the pattern/architecture for user creation right from the routes to how the response is sent. 
we want to separate the code from the express.js router
and also not pass the req or res object to the service layer.

**Comment by itzgeebee** [comment]
@jakazzy This tagging functionality is the same as adding tags to posts right?

**Comment by itzgeebee** [comment]
@beblicarl This doesn't happen to be part of what you are working on right?

**Comment by jakazzy** [comment]
> @jakazzy This tagging functionality is the same as adding tags to posts right?

yes, you are right
