### ISSUE TITLE
Send email with redirecting url when new user is created

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#95]
## Task Description

Describe the task to be completed.
When an admin creates a new user, we want to send a  URL that logs newly created users into the dashboard. 
( **extra information**:  The URL sends users to the dashboard for them to update their profile information as part of onboarding.)
ps.  @roji-tech @Aajibolah to ensure we are on track, does this capture what was discussed yesterday?

## Technical Considerations

We want to emit a new event  `new user signed up with email: ${email}`
Then a listener sends the email to the user.

**Comment by jocrah** [comment]
I think the user creation flow has changed considerably since this was created so this can be closed
